### ISSUE TITLE
Outline Arm and gripper commands and subsystems to fit with the arm and gripper designs

### ISSUE THREAD

**Issue by tjamesw123** [FRC-Team-620/Warbots2023#52]
Arm uses one or two NEOs to control a winch that moves gas springs for the upwards and downwards motion. (Need to find the length of the winch straps in meters)
Arm also uses another NEO to control another winch that moves another set of gas springs for the outwards and inwards motion (Need to find the length of these winch straps in meters as well)
Grabber uses one piston/solenoid to close and open the grabber and the grabber also uses a NEO to spin the wheels on the grabber inwards and outwards to better manipulate the Game Pieces

**Comment by m10653** [comment]
From your description it sounds like we need at least 2 subsystems.

- [x] Arm Subsystem (Contains both joints for the arm)
- [x] End Effector Subsystem (Intake and grabber)

For handling the control of the arm joints instead of relying on the length of the straps (Winding of straps on a wench can very in length) if we can get mech/electronics to put potentiometers or absolute encoders on the joints it would make the arm much easer to control via software.
